# Generated by Django 5.2.6 on 2026-04-07 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_userprofile_post_postcomment_postlike"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "phone",
                    models.CharField(max_length=11, unique=True, verbose_name="手机号"),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=128, verbose_name="密码哈希"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "普通用户"), ("doctor", "医生")],
                        default="user",
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="真实姓名"
                    ),
                ),
                (
                    "hospital",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="执业医院"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户账号",
                "verbose_name_plural": "用户账号",
                "db_table": "user_account",
            },
        ),
    ]
